version: "2"
services:

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - nginx_volume:/etc/nginx
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "82:82"

  web:
    build: .
    pull_policy: build
    restart: always
    command: gunicorn dravenverse.wsgi:application --bind 0.0.0.0:8002
    env_file: stack.env

    volumes:
      # - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8002:8002"
    depends_on:
      - db
    working_dir: /app

  db:
    image: postgres:16
    container_name: dravenverse_db
    restart: always
    env_file: stack.env

    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - "5435"
    ports:
      - 5435:5435

  backup:
    image: eeshugerman/postgres-backup-s3:16
    env_file: stack.env
    restart: always
    environment:
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 14

volumes:
  postgres_data:
  nginx_volume:
  media_volume:
  static_volume: