# Generated by Django 5.0.6 on 2024-08-23 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('image', models.ImageField(upload_to='dravenverse', verbose_name='Image')),
                ('birthplace', ckeditor.fields.RichTextField(verbose_name='Birth Place')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('backstory', ckeditor.fields.RichTextField(verbose_name='Backstory')),
                ('description_short', models.TextField(verbose_name='Short Description')),
                ('role', models.TextField(verbose_name='Role')),
            ],
        ),
    ]
