# Generated by Django 5.0.6 on 2024-08-23 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historicalcharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='attack_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Attack Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='defense_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Defense Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='hp_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='HP Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Intelligence Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='speed_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Speed Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='attack_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Attack Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='defense_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Defense Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='hp_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='HP Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='intelligence_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Intelligence Stats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='speed_stats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Speed Stats'),
            preserve_default=False,
        ),
    ]
