# Generated by Django 5.0.6 on 2024-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stats_character_attack_stats_character_defense_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='banner',
            field=models.ImageField(default='', upload_to='dravenverse', verbose_name='Banner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='banner',
            field=models.TextField(default='', max_length=100, verbose_name='Banner'),
            preserve_default=False,
        ),
    ]
